package com.urbanmatrix.mavlink.definitions.uavionix

import com.urbanmatrix.mavlink.api.GeneratedMavEnum
import com.urbanmatrix.mavlink.api.MavEnum
import kotlin.Long

/**
 * Definitions for aircraft size
 */
@GeneratedMavEnum
public enum class UavionixAdsbOutCfgAircraftSize(
  public override val `value`: Long,
) : MavEnum {
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_NO_DATA(0L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L15M_W23M(1L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L25M_W28P5M(2L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L25_34M(3L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L35_33M(4L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L35_38M(5L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L45_39P5M(6L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L45_45M(7L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L55_45M(8L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L55_52M(9L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L65_59P5M(10L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L65_67M(11L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L75_W72P5M(12L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L75_W80M(13L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L85_W80M(14L),
  UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L85_W90M(15L),
  ;

  public companion object {
    public fun getEntryFromValueOrNull(v: Long): UavionixAdsbOutCfgAircraftSize? = when (v) {
      0L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_NO_DATA
      1L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L15M_W23M
      2L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L25M_W28P5M
      3L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L25_34M
      4L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L35_33M
      5L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L35_38M
      6L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L45_39P5M
      7L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L45_45M
      8L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L55_45M
      9L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L55_52M
      10L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L65_59P5M
      11L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L65_67M
      12L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L75_W72P5M
      13L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L75_W80M
      14L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L85_W80M
      15L -> UAVIONIX_ADSB_OUT_CFG_AIRCRAFT_SIZE_L85_W90M
      else -> null
    }
  }
}
