package xyz.urbanmatrix.mavlink.definitions.ardupilotmega

import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.ByteArray
import kotlin.Int
import kotlin.Unit
import xyz.urbanmatrix.mavlink.api.GeneratedMavField
import xyz.urbanmatrix.mavlink.api.GeneratedMavMessage
import xyz.urbanmatrix.mavlink.api.MavDeserializer
import xyz.urbanmatrix.mavlink.api.MavMessage
import xyz.urbanmatrix.mavlink.serialization.decodeUint16
import xyz.urbanmatrix.mavlink.serialization.decodeUint8
import xyz.urbanmatrix.mavlink.serialization.encodeUint16
import xyz.urbanmatrix.mavlink.serialization.encodeUint8
import xyz.urbanmatrix.mavlink.serialization.truncateZeros

/**
 * Status generated by radio.
 */
@GeneratedMavMessage(
  id = 166,
  crc = 21,
)
public data class Radio(
  /**
   * Local signal strength.
   */
  @GeneratedMavField(type = "uint8_t")
  public val rssi: Int = 0,
  /**
   * Remote signal strength.
   */
  @GeneratedMavField(type = "uint8_t")
  public val remrssi: Int = 0,
  /**
   * How full the tx buffer is.
   */
  @GeneratedMavField(type = "uint8_t")
  public val txbuf: Int = 0,
  /**
   * Background noise level.
   */
  @GeneratedMavField(type = "uint8_t")
  public val noise: Int = 0,
  /**
   * Remote background noise level.
   */
  @GeneratedMavField(type = "uint8_t")
  public val remnoise: Int = 0,
  /**
   * Receive errors.
   */
  @GeneratedMavField(type = "uint16_t")
  public val rxerrors: Int = 0,
  /**
   * Count of error corrected packets.
   */
  @GeneratedMavField(type = "uint16_t")
  public val fixed: Int = 0,
) : MavMessage<Radio> {
  public override val instanceMetadata: MavMessage.Metadata<Radio> = METADATA

  public override fun serializeV1(): ByteArray {
    val outputBuffer = ByteBuffer.allocate(SIZE_V1).order(ByteOrder.LITTLE_ENDIAN)
    outputBuffer.encodeUint16(rxerrors)
    outputBuffer.encodeUint16(fixed)
    outputBuffer.encodeUint8(rssi)
    outputBuffer.encodeUint8(remrssi)
    outputBuffer.encodeUint8(txbuf)
    outputBuffer.encodeUint8(noise)
    outputBuffer.encodeUint8(remnoise)
    return outputBuffer.array()
  }

  public override fun serializeV2(): ByteArray {
    val outputBuffer = ByteBuffer.allocate(SIZE_V2).order(ByteOrder.LITTLE_ENDIAN)
    outputBuffer.encodeUint16(rxerrors)
    outputBuffer.encodeUint16(fixed)
    outputBuffer.encodeUint8(rssi)
    outputBuffer.encodeUint8(remrssi)
    outputBuffer.encodeUint8(txbuf)
    outputBuffer.encodeUint8(noise)
    outputBuffer.encodeUint8(remnoise)
    return outputBuffer.array().truncateZeros()
  }

  public companion object {
    private const val ID: Int = 166

    private const val CRC: Int = 21

    private const val SIZE_V1: Int = 9

    private const val SIZE_V2: Int = 9

    private val DESERIALIZER: MavDeserializer<Radio> = MavDeserializer { bytes ->
      val inputBuffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
      val rxerrors = inputBuffer.decodeUint16()
      val fixed = inputBuffer.decodeUint16()
      val rssi = inputBuffer.decodeUint8()
      val remrssi = inputBuffer.decodeUint8()
      val txbuf = inputBuffer.decodeUint8()
      val noise = inputBuffer.decodeUint8()
      val remnoise = inputBuffer.decodeUint8()

      Radio(
        rssi = rssi,
        remrssi = remrssi,
        txbuf = txbuf,
        noise = noise,
        remnoise = remnoise,
        rxerrors = rxerrors,
        fixed = fixed,
      )
    }


    private val METADATA: MavMessage.Metadata<Radio> = MavMessage.Metadata(ID, CRC, DESERIALIZER)

    public val classMetadata: MavMessage.Metadata<Radio> = METADATA

    public fun builder(builderAction: Builder.() -> Unit) = Builder().apply(builderAction).build()
  }

  public class Builder {
    public var rssi: Int = 0

    public var remrssi: Int = 0

    public var txbuf: Int = 0

    public var noise: Int = 0

    public var remnoise: Int = 0

    public var rxerrors: Int = 0

    public var fixed: Int = 0

    public fun build(): Radio = Radio(
      rssi = rssi,
      remrssi = remrssi,
      txbuf = txbuf,
      noise = noise,
      remnoise = remnoise,
      rxerrors = rxerrors,
      fixed = fixed,
    )
  }
}
