package com.urbanmatrix.mavlink.ardupilotmega

import com.urbanmatrix.mavlink.api.AbstractMavDialect
import com.urbanmatrix.mavlink.common.CommonDialect
import com.urbanmatrix.mavlink.icarous.IcarousDialect
import com.urbanmatrix.mavlink.uAvionix.UavionixDialect

public object ArdupilotmegaDialect : AbstractMavDialect(
  setOf(
    IcarousDialect
    UavionixDialect
    CommonDialect
  ), 
  mapOf(
    SensorOffsets.classMetadata.id to SensorOffsets.classMetadata,
    SetMagOffsets.classMetadata.id to SetMagOffsets.classMetadata,
    Meminfo.classMetadata.id to Meminfo.classMetadata,
    ApAdc.classMetadata.id to ApAdc.classMetadata,
    DigicamConfigure.classMetadata.id to DigicamConfigure.classMetadata,
    DigicamControl.classMetadata.id to DigicamControl.classMetadata,
    MountConfigure.classMetadata.id to MountConfigure.classMetadata,
    MountControl.classMetadata.id to MountControl.classMetadata,
    MountStatus.classMetadata.id to MountStatus.classMetadata,
    FencePoint.classMetadata.id to FencePoint.classMetadata,
    FenceFetchPoint.classMetadata.id to FenceFetchPoint.classMetadata,
    Ahrs.classMetadata.id to Ahrs.classMetadata,
    Simstate.classMetadata.id to Simstate.classMetadata,
    Hwstatus.classMetadata.id to Hwstatus.classMetadata,
    Radio.classMetadata.id to Radio.classMetadata,
    LimitsStatus.classMetadata.id to LimitsStatus.classMetadata,
    Wind.classMetadata.id to Wind.classMetadata,
    Data16.classMetadata.id to Data16.classMetadata,
    Data32.classMetadata.id to Data32.classMetadata,
    Data64.classMetadata.id to Data64.classMetadata,
    Data96.classMetadata.id to Data96.classMetadata,
    Rangefinder.classMetadata.id to Rangefinder.classMetadata,
    AirspeedAutocal.classMetadata.id to AirspeedAutocal.classMetadata,
    RallyPoint.classMetadata.id to RallyPoint.classMetadata,
    RallyFetchPoint.classMetadata.id to RallyFetchPoint.classMetadata,
    CompassmotStatus.classMetadata.id to CompassmotStatus.classMetadata,
    Ahrs2.classMetadata.id to Ahrs2.classMetadata,
    CameraStatus.classMetadata.id to CameraStatus.classMetadata,
    CameraFeedback.classMetadata.id to CameraFeedback.classMetadata,
    Battery2.classMetadata.id to Battery2.classMetadata,
    Ahrs3.classMetadata.id to Ahrs3.classMetadata,
    AutopilotVersionRequest.classMetadata.id to AutopilotVersionRequest.classMetadata,
    RemoteLogDataBlock.classMetadata.id to RemoteLogDataBlock.classMetadata,
    RemoteLogBlockStatus.classMetadata.id to RemoteLogBlockStatus.classMetadata,
    LedControl.classMetadata.id to LedControl.classMetadata,
    MagCalProgress.classMetadata.id to MagCalProgress.classMetadata,
    EkfStatusReport.classMetadata.id to EkfStatusReport.classMetadata,
    PidTuning.classMetadata.id to PidTuning.classMetadata,
    Deepstall.classMetadata.id to Deepstall.classMetadata,
    GimbalReport.classMetadata.id to GimbalReport.classMetadata,
    GimbalControl.classMetadata.id to GimbalControl.classMetadata,
    GimbalTorqueCmdReport.classMetadata.id to GimbalTorqueCmdReport.classMetadata,
    GoproHeartbeat.classMetadata.id to GoproHeartbeat.classMetadata,
    GoproGetRequest.classMetadata.id to GoproGetRequest.classMetadata,
    GoproGetResponse.classMetadata.id to GoproGetResponse.classMetadata,
    GoproSetRequest.classMetadata.id to GoproSetRequest.classMetadata,
    GoproSetResponse.classMetadata.id to GoproSetResponse.classMetadata,
    Rpm.classMetadata.id to Rpm.classMetadata,
    DeviceOpRead.classMetadata.id to DeviceOpRead.classMetadata,
    DeviceOpReadReply.classMetadata.id to DeviceOpReadReply.classMetadata,
    DeviceOpWrite.classMetadata.id to DeviceOpWrite.classMetadata,
    DeviceOpWriteReply.classMetadata.id to DeviceOpWriteReply.classMetadata,
    AdapTuning.classMetadata.id to AdapTuning.classMetadata,
    VisionPositionDelta.classMetadata.id to VisionPositionDelta.classMetadata,
    AoaSsa.classMetadata.id to AoaSsa.classMetadata,
    EscTelemetry1To4.classMetadata.id to EscTelemetry1To4.classMetadata,
    EscTelemetry5To8.classMetadata.id to EscTelemetry5To8.classMetadata,
    EscTelemetry9To12.classMetadata.id to EscTelemetry9To12.classMetadata,
    OsdParamConfig.classMetadata.id to OsdParamConfig.classMetadata,
    OsdParamConfigReply.classMetadata.id to OsdParamConfigReply.classMetadata,
    OsdParamShowConfig.classMetadata.id to OsdParamShowConfig.classMetadata,
    OsdParamShowConfigReply.classMetadata.id to OsdParamShowConfigReply.classMetadata,
    ObstacleDistance3d.classMetadata.id to ObstacleDistance3d.classMetadata,
    WaterDepth.classMetadata.id to WaterDepth.classMetadata,
    McuStatus.classMetadata.id to McuStatus.classMetadata,
  )
)
