name: Publish library - definitions, connections and adapter modules

on:
  push:
    branches: [ "multiplatform" ]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "publish-library"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up gradle
        uses: gradle/gradle-build-action@v2

      - name: Write secrets to gradle.properties
        run: |
          echo "mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}" >> gradle.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}" >> gradle.properties

          echo "signingInMemoryKey=${{ secrets.SIGNING_IN_MEMORY_KEY }}" >> gradle.properties
          echo "signingInMemoryKeyId=${{ secrets.SIGNING_IN_MEMORY_KEY_ID }}" >> gradle.properties
          echo "signingInMemoryKeyPassword=${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}" >> gradle.properties

      - name: Publish plugin
        run: ./gradlew publishLibrary

      - name: Close and release plugin
        run: ./gradlew closeAndReleaseLibrary
