name: Publish plugin - api, serialization and generator modules

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: "publish-plugin"
  cancel-in-progress: true

jobs:
  publish-plugin:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Write secrets to gradle.properties
        run: |
          echo "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" >> gradle.properties
          echo "gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" >> gradle.properties

          echo "mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}" >> gradle.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}" >> gradle.properties

          echo "signingInMemoryKey=${{ secrets.SIGNING_IN_MEMORY_KEY }}" >> gradle.properties
          echo "signingInMemoryKeyId=${{ secrets.SIGNING_IN_MEMORY_KEY_ID }}" >> gradle.properties
          echo "signingInMemoryKeyPassword=${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}" >> gradle.properties

      - name: Publish plugin
        run: ./gradlew publishPlugin
